apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vensav-deployer
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - jobs
  - pods
  - services
  - daemonsets
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - delete
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - create
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - list
  - watch
  - delete

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: vensav-ml-data-deployer
  labels:
    ml-data-engg-full-access: "True"
    minio-full-access: "True"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vensav-ml-data-deployer-ml-data-engg-access
  labels:
    service-account: vensav-ml-data-deployer
    cluster-role: vensav-deployer
    ml-data-engg-full-access: "True"
  namespace: ml-data-engg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vensav-deployer
subjects:
- kind: ServiceAccount
  name: vensav-ml-data-deployer
  namespace: ml-data-engg

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vensav-ml-data-deployer-minio-access
  labels:
    service-account: vensav-ml-data-deployer
    cluster-role: vensav-deployer
    minio-full-access: "True"
  namespace: minio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vensav-deployer
subjects:
- kind: ServiceAccount
  name: vensav-ml-data-deployer
  namespace: ml-data-engg