# https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-py-pi.yaml
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Support for Python is experimental, and requires building SNAPSHOT image of Apache Spark,
# with `imagePullPolicy` set to Always

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-operator-python-test
  namespace: ml-data-engg
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: vensav/spark-operator-driver:3.3.0-scala_2.12-jre_17-slim-bullseye
  imagePullPolicy: Always
  mainApplicationFile: local:///app/spark_on_k8s/main.py
  sparkVersion: "3.3.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.3.0
    serviceAccount: vensav-ml-data-deployer
    envSecretKeyRefs:
      S3_HOST_URL:
        name: minio-api-client-credentials
        key: MINIO_HOST_URL
      AWS_ACCESS_KEY_ID:
        name: minio-api-client-credentials
        key: MINIO_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY:
        name: minio-api-client-credentials
        key: MINIO_SECRET_KEY
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.3.0
    envSecretKeyRefs:
      S3_HOST_URL:
        name: minio-api-client-credentials
        key: MINIO_HOST_URL
      AWS_ACCESS_KEY_ID:
        name: minio-api-client-credentials
        key: MINIO_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY:
        name: minio-api-client-credentials
        key: MINIO_SECRET_KEY
  deps:
    jars:
      - https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar
      - https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.298/aws-java-sdk-bundle-1.12.298.jar

